micronaut:
  application:
    name: hrWorker
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/ep_workers
    driverClassName: org.postgresql.Driver
    username: postgres
    password: jjbatera4
    schema-generate: UPDATE
    dialect: POSTGRES
netty:
  default:
    allocator:
      max-order: 3
jpa.default.properties.hibernate.hbm2ddl.auto: update
